version: '3.8'

services:
  model:
    image: char
    build:
      context: .
      shm_size: '16gb'
    volumes:
      - ./:/workspace
      - /pth/to/dataset/:/data/EPIC-KITCHENS/:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
